Search.appendIndex(
    [
                {
            "fqsen": "\\Alumnos",
            "name": "Alumnos",
            "summary": "",
            "url": "classes/Alumnos.html"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Esta\u0020funcion\u0020instancia\u0020el\u0020objeto",
            "url": "classes/Alumnos.html#method___construct"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Funcion\u0020para\u0020obtener\u0020el\u0020valor\u0020de\u0020las\u0020variablles\nde\u0020la\u0020instancia",
            "url": "classes/Alumnos.html#method___get"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Asigna\u0020valores\u0020a\u0020las\u0020variables\u0020de\u0020la\u0020instancia",
            "url": "classes/Alumnos.html#method___set"
        },                {
            "fqsen": "\\Alumnos\u003A\u003AcrearAlumno\u0028\u0029",
            "name": "crearAlumno",
            "summary": "Crea\u0020un\u0020nuevo\u0020alumno\u0020ejecutando\u0020un\u0020script\u0020sql\u0020con\u0020los\ndatos\u0020de\u0020la\u0020instancia\u0020alumnno",
            "url": "classes/Alumnos.html#method_crearAlumno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003AobtenerAlumnosCurso\u0028\u0029",
            "name": "obtenerAlumnosCurso",
            "summary": "",
            "url": "classes/Alumnos.html#method_obtenerAlumnosCurso"
        },                {
            "fqsen": "\\Alumnos\u003A\u003AobtenerAlumno\u0028\u0029",
            "name": "obtenerAlumno",
            "summary": "Obtiene\u0020los\u0020datos\u0020de\u0020un\u0020alumno\u0020especifico",
            "url": "classes/Alumnos.html#method_obtenerAlumno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003AborrarAlumno\u0028\u0029",
            "name": "borrarAlumno",
            "summary": "Borra\u0020a\u0020un\u0020alumno\u0020especifico\u0020de\u0020la\u0020lista",
            "url": "classes/Alumnos.html#method_borrarAlumno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003AeditarAlumno\u0028\u0029",
            "name": "editarAlumno",
            "summary": "Edita\u0020a\u0020un\u0020alumno\u0020con\u0020los\u0020valores\u0020ingresados",
            "url": "classes/Alumnos.html#method_editarAlumno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003AobtenerAlumnos\u0028\u0029",
            "name": "obtenerAlumnos",
            "summary": "Obtiene\u0020una\u0020lista\u0020de\u0020alumnos,\u0020si\u0020\u0024idCurso\u0020se\u0020deja\u0020por\u0020defecto\nentonces\u0020llama\u0020a\u0020todos\u0020los\u0020alumnos,\u0020si\u0020se\u0020cambia\u0020a\u0020un\u0020valor\u0020entero\nllama\u0020a\u0020los\u0020alumnos\u0020que\u0020pertenezcan\u0020a\u0020la\u0020lista\u0020de\u0020un\u0020curso\u0020especifico",
            "url": "classes/Alumnos.html#method_obtenerAlumnos"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Alumnos.html#property_db"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024id_alumno",
            "name": "id_alumno",
            "summary": "",
            "url": "classes/Alumnos.html#property_id_alumno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024id_curso",
            "name": "id_curso",
            "summary": "",
            "url": "classes/Alumnos.html#property_id_curso"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024run",
            "name": "run",
            "summary": "",
            "url": "classes/Alumnos.html#property_run"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "",
            "url": "classes/Alumnos.html#property_nombre"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024apellido_paterno",
            "name": "apellido_paterno",
            "summary": "",
            "url": "classes/Alumnos.html#property_apellido_paterno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024apellido_materno",
            "name": "apellido_materno",
            "summary": "",
            "url": "classes/Alumnos.html#property_apellido_materno"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024fecha_nacimiento",
            "name": "fecha_nacimiento",
            "summary": "",
            "url": "classes/Alumnos.html#property_fecha_nacimiento"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Alumnos.html#property_email"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024direccion",
            "name": "direccion",
            "summary": "",
            "url": "classes/Alumnos.html#property_direccion"
        },                {
            "fqsen": "\\Alumnos\u003A\u003A\u0024celular",
            "name": "celular",
            "summary": "",
            "url": "classes/Alumnos.html#property_celular"
        },                {
            "fqsen": "\\Asignatura",
            "name": "Asignatura",
            "summary": "",
            "url": "classes/Asignatura.html"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Asignatura.html#method___construct"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Asignatura.html#method___get"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "",
            "url": "classes/Asignatura.html#method___set"
        },                {
            "fqsen": "\\Asignatura\u003A\u003AagregarAcurso\u0028\u0029",
            "name": "agregarAcurso",
            "summary": "",
            "url": "classes/Asignatura.html#method_agregarAcurso"
        },                {
            "fqsen": "\\Asignatura\u003A\u003AobtenerAsignaturas\u0028\u0029",
            "name": "obtenerAsignaturas",
            "summary": "",
            "url": "classes/Asignatura.html#method_obtenerAsignaturas"
        },                {
            "fqsen": "\\Asignatura\u003A\u003AobtenerAsignaturasCurso\u0028\u0029",
            "name": "obtenerAsignaturasCurso",
            "summary": "",
            "url": "classes/Asignatura.html#method_obtenerAsignaturasCurso"
        },                {
            "fqsen": "\\Asignatura\u003A\u003AcrearAsignatura\u0028\u0029",
            "name": "crearAsignatura",
            "summary": "",
            "url": "classes/Asignatura.html#method_crearAsignatura"
        },                {
            "fqsen": "\\Asignatura\u003A\u003AborrarAsignatura\u0028\u0029",
            "name": "borrarAsignatura",
            "summary": "",
            "url": "classes/Asignatura.html#method_borrarAsignatura"
        },                {
            "fqsen": "\\Asignatura\u003A\u003AobtenerTablaAsignaturas\u0028\u0029",
            "name": "obtenerTablaAsignaturas",
            "summary": "",
            "url": "classes/Asignatura.html#method_obtenerTablaAsignaturas"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Asignatura.html#property_db"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A\u0024id_asignatura",
            "name": "id_asignatura",
            "summary": "",
            "url": "classes/Asignatura.html#property_id_asignatura"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A\u0024id_empleado",
            "name": "id_empleado",
            "summary": "",
            "url": "classes/Asignatura.html#property_id_empleado"
        },                {
            "fqsen": "\\Asignatura\u003A\u003A\u0024nombre_asignatura",
            "name": "nombre_asignatura",
            "summary": "",
            "url": "classes/Asignatura.html#property_nombre_asignatura"
        },                {
            "fqsen": "\\Asistencia",
            "name": "Asistencia",
            "summary": "",
            "url": "classes/Asistencia.html"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Esta\u0020funcion\u0020instancia\u0020el\u0020objeto",
            "url": "classes/Asistencia.html#method___construct"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Funcion\u0020para\u0020obtener\u0020el\u0020valor\u0020de\u0020las\u0020variablles\nde\u0020la\u0020instancia",
            "url": "classes/Asistencia.html#method___get"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Asigna\u0020valores\u0020a\u0020las\u0020variables\u0020de\u0020la\u0020instancia",
            "url": "classes/Asistencia.html#method___set"
        },                {
            "fqsen": "\\Asistencia\u003A\u003AcrearAsistencia\u0028\u0029",
            "name": "crearAsistencia",
            "summary": "",
            "url": "classes/Asistencia.html#method_crearAsistencia"
        },                {
            "fqsen": "\\Asistencia\u003A\u003AobtenerAsistencia\u0028\u0029",
            "name": "obtenerAsistencia",
            "summary": "",
            "url": "classes/Asistencia.html#method_obtenerAsistencia"
        },                {
            "fqsen": "\\Asistencia\u003A\u003AborrarAsistencia\u0028\u0029",
            "name": "borrarAsistencia",
            "summary": "",
            "url": "classes/Asistencia.html#method_borrarAsistencia"
        },                {
            "fqsen": "\\Asistencia\u003A\u003AeditarAsistencia\u0028\u0029",
            "name": "editarAsistencia",
            "summary": "",
            "url": "classes/Asistencia.html#method_editarAsistencia"
        },                {
            "fqsen": "\\Asistencia\u003A\u003AobtenerAsistencias\u0028\u0029",
            "name": "obtenerAsistencias",
            "summary": "",
            "url": "classes/Asistencia.html#method_obtenerAsistencias"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Asistencia.html#property_db"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024id_asistencia",
            "name": "id_asistencia",
            "summary": "",
            "url": "classes/Asistencia.html#property_id_asistencia"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024id_alumno",
            "name": "id_alumno",
            "summary": "",
            "url": "classes/Asistencia.html#property_id_alumno"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024id_horario",
            "name": "id_horario",
            "summary": "",
            "url": "classes/Asistencia.html#property_id_horario"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024fecha",
            "name": "fecha",
            "summary": "",
            "url": "classes/Asistencia.html#property_fecha"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024observacion",
            "name": "observacion",
            "summary": "",
            "url": "classes/Asistencia.html#property_observacion"
        },                {
            "fqsen": "\\Asistencia\u003A\u003A\u0024estado_asistencia",
            "name": "estado_asistencia",
            "summary": "",
            "url": "classes/Asistencia.html#property_estado_asistencia"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "classes/Database.html"
        },                {
            "fqsen": "\\Database\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Instancia\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Database.html#method___construct"
        },                {
            "fqsen": "\\Database\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Obtiene\u0020toda\u0020la\u0020lista\u0020generada\u0020por\u0020el\u0020script\u0020sql",
            "url": "classes/Database.html#method_getAll"
        },                {
            "fqsen": "\\Database\u003A\u003Aconsult\u0028\u0029",
            "name": "consult",
            "summary": "Genera\u0020una\u0020consulta\u0020de\u0020una\u0020fila\u0020por\u0020el\u0020script\u0020sql",
            "url": "classes/Database.html#method_consult"
        },                {
            "fqsen": "\\Database\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Ejecuta\u0020el\u0020script\u0020sql\u0020para\u0020hacer\u0020un\u0020cambio\u0020en\u0020la\u0020tabla\nel\u0020valor\u0020quq\u0020retorna\u0020es\u0020un\u0020integer\u0020binario\u0020que\u0020devuelve\u0020si\nse\u0020cambio\u0020bien\u0020o\u0020si\u0020hubo\u0020un\u0020error",
            "url": "classes/Database.html#method_execute"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Database.html#property_db"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024sentence",
            "name": "sentence",
            "summary": "",
            "url": "classes/Database.html#property_sentence"
        },                {
            "fqsen": "\\Cursos",
            "name": "Cursos",
            "summary": "",
            "url": "classes/Cursos.html"
        },                {
            "fqsen": "\\Cursos\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Cursos.html#method___construct"
        },                {
            "fqsen": "\\Cursos\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Funcion\u0020para\u0020obtener\u0020el\u0020valor\u0020de\u0020las\u0020variablles\nde\u0020la\u0020instancia",
            "url": "classes/Cursos.html#method___get"
        },                {
            "fqsen": "\\Cursos\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Asigna\u0020valores\u0020a\u0020las\u0020variables\u0020de\u0020la\u0020instancia",
            "url": "classes/Cursos.html#method___set"
        },                {
            "fqsen": "\\Cursos\u003A\u003AcrearCurso\u0028\u0029",
            "name": "crearCurso",
            "summary": "crea\u0020un\u0020nuevo\u0020curso\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Cursos.html#method_crearCurso"
        },                {
            "fqsen": "\\Cursos\u003A\u003AobtenerCurso\u0028\u0029",
            "name": "obtenerCurso",
            "summary": "Obtiene\u0020los\u0020datos\u0020de\u0020un\u0020curso\u0020especifico",
            "url": "classes/Cursos.html#method_obtenerCurso"
        },                {
            "fqsen": "\\Cursos\u003A\u003AborrarCurso\u0028\u0029",
            "name": "borrarCurso",
            "summary": "Borra\u0020a\u0020un\u0020curso\u0020especifico\u0020de\u0020la\u0020lista",
            "url": "classes/Cursos.html#method_borrarCurso"
        },                {
            "fqsen": "\\Cursos\u003A\u003AeditarCurso\u0028\u0029",
            "name": "editarCurso",
            "summary": "Edita\u0020los\u0020datos\u0020de\u0020un\u0020curso",
            "url": "classes/Cursos.html#method_editarCurso"
        },                {
            "fqsen": "\\Cursos\u003A\u003AobtenerCursos\u0028\u0029",
            "name": "obtenerCursos",
            "summary": "Obtiene\u0020los\u0020datos\u0020de\u0020la\u0020tabla\u0020cursos\u0020y\u0020los\u0020adjunta\u0020en\u0020un\u0020array\nusualmente\u0020para\u0020dataTables",
            "url": "classes/Cursos.html#method_obtenerCursos"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Cursos.html#property_db"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024id_curso",
            "name": "id_curso",
            "summary": "",
            "url": "classes/Cursos.html#property_id_curso"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024id_libro",
            "name": "id_libro",
            "summary": "",
            "url": "classes/Cursos.html#property_id_libro"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024anio",
            "name": "anio",
            "summary": "",
            "url": "classes/Cursos.html#property_anio"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024nivel",
            "name": "nivel",
            "summary": "",
            "url": "classes/Cursos.html#property_nivel"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024seccion",
            "name": "seccion",
            "summary": "",
            "url": "classes/Cursos.html#property_seccion"
        },                {
            "fqsen": "\\Cursos\u003A\u003A\u0024n_sala",
            "name": "n_sala",
            "summary": "",
            "url": "classes/Cursos.html#property_n_sala"
        },                {
            "fqsen": "\\Empleado",
            "name": "Empleado",
            "summary": "",
            "url": "classes/Empleado.html"
        },                {
            "fqsen": "\\Empleado\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Esta\u0020funcion\u0020instancia\u0020el\u0020objeto",
            "url": "classes/Empleado.html#method___construct"
        },                {
            "fqsen": "\\Empleado\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Funcion\u0020para\u0020obtener\u0020el\u0020valor\u0020de\u0020las\u0020variablles\nde\u0020la\u0020instancia",
            "url": "classes/Empleado.html#method___get"
        },                {
            "fqsen": "\\Empleado\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Asgiana\u0020valores\u0020a\u0020una\u0020variable\u0020de\u0020la\u0020instancia",
            "url": "classes/Empleado.html#method___set"
        },                {
            "fqsen": "\\Empleado\u003A\u003AiniciarSesion\u0028\u0029",
            "name": "iniciarSesion",
            "summary": "Con\u0020esta\u0020funcion\u0020se\u0020comparara\u0020los\u0020datos\u0020con\u0020la\u0020informacion\u0020de\u0020la\u0020base\u0020de\u0020datos\ny\u0020asi\u0020saber\u0020si\u0020estan\u0020correctos",
            "url": "classes/Empleado.html#method_iniciarSesion"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024jefatura",
            "name": "jefatura",
            "summary": "",
            "url": "classes/Empleado.html#property_jefatura"
        },                {
            "fqsen": "\\Empleado\u003A\u003AcrearEmpleado\u0028\u0029",
            "name": "crearEmpleado",
            "summary": "Crea\u0020un\u0020nuevo\u0020empleado\u0020ejecutando\u0020un\u0020script\u0020sql\u0020con\u0020los\ndatos\u0020de\u0020la\u0020instancia\u0020alumnno",
            "url": "classes/Empleado.html#method_crearEmpleado"
        },                {
            "fqsen": "\\Empleado\u003A\u003AobtenerEmpleado\u0028\u0029",
            "name": "obtenerEmpleado",
            "summary": "Se\u0020obtiene\u0020un\u0020empleado\u0020especifico\u0020segun\u0020su\u0020id",
            "url": "classes/Empleado.html#method_obtenerEmpleado"
        },                {
            "fqsen": "\\Empleado\u003A\u003AborrarEmpleado\u0028\u0029",
            "name": "borrarEmpleado",
            "summary": "Esta\u0020funcion\u0020borra\u0020un\u0020empleado\u0020que\u0020este\u0020registrado\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Empleado.html#method_borrarEmpleado"
        },                {
            "fqsen": "\\Empleado\u003A\u003AeditarEmpleado\u0028\u0029",
            "name": "editarEmpleado",
            "summary": "Este\u0020metodo\u0020modifica\u0020los\u0020datos\u0020de\u0020algun\u0020empleado\u0020especifico\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Empleado.html#method_editarEmpleado"
        },                {
            "fqsen": "\\Empleado\u003A\u003AobtenerEmpleados\u0028\u0029",
            "name": "obtenerEmpleados",
            "summary": "Obtendra\u0020todos\u0020los\u0020empleados\u0020de\u0020la\u0020tabla\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Empleado.html#method_obtenerEmpleados"
        },                {
            "fqsen": "\\Empleado\u003A\u003AobtenerProfesores\u0028\u0029",
            "name": "obtenerProfesores",
            "summary": "",
            "url": "classes/Empleado.html#method_obtenerProfesores"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Empleado.html#property_db"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024id_empleado",
            "name": "id_empleado",
            "summary": "",
            "url": "classes/Empleado.html#property_id_empleado"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024run",
            "name": "run",
            "summary": "",
            "url": "classes/Empleado.html#property_run"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024pw",
            "name": "pw",
            "summary": "",
            "url": "classes/Empleado.html#property_pw"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Empleado.html#property_email"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "",
            "url": "classes/Empleado.html#property_nombre"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024apellido_paterno",
            "name": "apellido_paterno",
            "summary": "",
            "url": "classes/Empleado.html#property_apellido_paterno"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024apellido_materno",
            "name": "apellido_materno",
            "summary": "",
            "url": "classes/Empleado.html#property_apellido_materno"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024fecha_nacimiento",
            "name": "fecha_nacimiento",
            "summary": "",
            "url": "classes/Empleado.html#property_fecha_nacimiento"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024direccion",
            "name": "direccion",
            "summary": "",
            "url": "classes/Empleado.html#property_direccion"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024telefono",
            "name": "telefono",
            "summary": "",
            "url": "classes/Empleado.html#property_telefono"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024celular",
            "name": "celular",
            "summary": "",
            "url": "classes/Empleado.html#property_celular"
        },                {
            "fqsen": "\\Empleado\u003A\u003A\u0024rol",
            "name": "rol",
            "summary": "",
            "url": "classes/Empleado.html#property_rol"
        },                {
            "fqsen": "\\LibroCursos",
            "name": "LibroCursos",
            "summary": "",
            "url": "classes/LibroCursos.html"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Esta\u0020funcion\u0020instancia\u0020el\u0020objeto",
            "url": "classes/LibroCursos.html#method___construct"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Funcion\u0020para\u0020obtener\u0020el\u0020valor\u0020de\u0020las\u0020variablles\nde\u0020la\u0020instancia",
            "url": "classes/LibroCursos.html#method___get"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Asigna\u0020valores\u0020a\u0020las\u0020variables\u0020de\u0020la\u0020instancia",
            "url": "classes/LibroCursos.html#method___set"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AcrearEvaluacion\u0028\u0029",
            "name": "crearEvaluacion",
            "summary": "Esta\u0020funcion\u0020ingresa\u0020una\u0020nueva\u0020evaluacion\u0020a\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/LibroCursos.html#method_crearEvaluacion"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AborrarEvaluacion\u0028\u0029",
            "name": "borrarEvaluacion",
            "summary": "Borra\u0020una\u0020evaluacion\u0020de\u0020la\u0020tabla\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/LibroCursos.html#method_borrarEvaluacion"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AeditarEvaluacion\u0028\u0029",
            "name": "editarEvaluacion",
            "summary": "Edita\u0020los\u0020datos\u0020de\u0020alguna\u0020evaluacion",
            "url": "classes/LibroCursos.html#method_editarEvaluacion"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AobtenerEvaluaciones\u0028\u0029",
            "name": "obtenerEvaluaciones",
            "summary": "Lista\u0020las\u0020evaluaciones\u0020para\u0020ser\u0020utilizados\u0020en\u0020alguna\u0020tabla",
            "url": "classes/LibroCursos.html#method_obtenerEvaluaciones"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/LibroCursos.html#property_db"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024id_evaluacion",
            "name": "id_evaluacion",
            "summary": "",
            "url": "classes/LibroCursos.html#property_id_evaluacion"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024id_alumno",
            "name": "id_alumno",
            "summary": "",
            "url": "classes/LibroCursos.html#property_id_alumno"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024id_asignatura",
            "name": "id_asignatura",
            "summary": "",
            "url": "classes/LibroCursos.html#property_id_asignatura"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024contenido",
            "name": "contenido",
            "summary": "",
            "url": "classes/LibroCursos.html#property_contenido"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024observacion",
            "name": "observacion",
            "summary": "",
            "url": "classes/LibroCursos.html#property_observacion"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024fecha",
            "name": "fecha",
            "summary": "",
            "url": "classes/LibroCursos.html#property_fecha"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024nota",
            "name": "nota",
            "summary": "",
            "url": "classes/LibroCursos.html#property_nota"
        },                {
            "fqsen": "\\Horario",
            "name": "Horario",
            "summary": "",
            "url": "classes/Horario.html"
        },                {
            "fqsen": "\\Horario\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Esta\u0020funcion\u0020instancia\u0020el\u0020objeto",
            "url": "classes/Horario.html#method___construct"
        },                {
            "fqsen": "\\Horario\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Funcion\u0020para\u0020obtener\u0020el\u0020valor\u0020de\u0020las\u0020variablles\nde\u0020la\u0020instancia",
            "url": "classes/Horario.html#method___get"
        },                {
            "fqsen": "\\Horario\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Asigna\u0020valores\u0020a\u0020las\u0020variables\u0020de\u0020la\u0020instancia",
            "url": "classes/Horario.html#method___set"
        },                {
            "fqsen": "\\Horario\u003A\u003AcrearHorario\u0028\u0029",
            "name": "crearHorario",
            "summary": "Crea\u0020un\u0020nuevo\u0020horario\u0020que\u0020se\u0020sube\u0020a\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Horario.html#method_crearHorario"
        },                {
            "fqsen": "\\Horario\u003A\u003AobtenerHorario\u0028\u0029",
            "name": "obtenerHorario",
            "summary": "",
            "url": "classes/Horario.html#method_obtenerHorario"
        },                {
            "fqsen": "\\Horario\u003A\u003AborrarHorario\u0028\u0029",
            "name": "borrarHorario",
            "summary": "Borra\u0020a\u0020un\u0020horario\u0020especifico\u0020de\u0020la\u0020lista",
            "url": "classes/Horario.html#method_borrarHorario"
        },                {
            "fqsen": "\\Horario\u003A\u003AeditarHorario\u0028\u0029",
            "name": "editarHorario",
            "summary": "Edita\u0020a\u0020un\u0020horario\u0020con\u0020los\u0020valores\u0020ingresados",
            "url": "classes/Horario.html#method_editarHorario"
        },                {
            "fqsen": "\\Horario\u003A\u003AobtenerHorarios\u0028\u0029",
            "name": "obtenerHorarios",
            "summary": "",
            "url": "classes/Horario.html#method_obtenerHorarios"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Horario.html#property_db"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024id_horario",
            "name": "id_horario",
            "summary": "",
            "url": "classes/Horario.html#property_id_horario"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024id_curso",
            "name": "id_curso",
            "summary": "",
            "url": "classes/Horario.html#property_id_curso"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024id_asignatura",
            "name": "id_asignatura",
            "summary": "",
            "url": "classes/Horario.html#property_id_asignatura"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024id_libro",
            "name": "id_libro",
            "summary": "",
            "url": "classes/Horario.html#property_id_libro"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024fecha",
            "name": "fecha",
            "summary": "",
            "url": "classes/Horario.html#property_fecha"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024hora_inicio",
            "name": "hora_inicio",
            "summary": "",
            "url": "classes/Horario.html#property_hora_inicio"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024hora_final",
            "name": "hora_final",
            "summary": "",
            "url": "classes/Horario.html#property_hora_final"
        },                {
            "fqsen": "\\Horario\u003A\u003A\u0024asistencia_profesor",
            "name": "asistencia_profesor",
            "summary": "",
            "url": "classes/Horario.html#property_asistencia_profesor"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AcrearLibro\u0028\u0029",
            "name": "crearLibro",
            "summary": "Esta\u0020funcion\u0020crea\u0020un\u0020libro\u0020de\u0020curso\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/LibroCursos.html#method_crearLibro"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AobtenerLibroEmpleado\u0028\u0029",
            "name": "obtenerLibroEmpleado",
            "summary": "Con\u0020esta\u0020funcion\u0020podemos\u0020traer\u0020la\u0020informacion\u0020que\u0020corresponda\u0020de\u0020un\u0020libro\nespecificado\u0020con\u0020el\u0020id_libro",
            "url": "classes/LibroCursos.html#method_obtenerLibroEmpleado"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AborrarLibro\u0028\u0029",
            "name": "borrarLibro",
            "summary": "Borra\u0020a\u0020un\u0020libro\u0020especifico\u0020de\u0020la\u0020lista",
            "url": "classes/LibroCursos.html#method_borrarLibro"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AeditarLibro\u0028\u0029",
            "name": "editarLibro",
            "summary": "Edita\u0020a\u0020un\u0020Libro\u0020con\u0020los\u0020valores\u0020ingresados",
            "url": "classes/LibroCursos.html#method_editarLibro"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003AobtenerLibros\u0028\u0029",
            "name": "obtenerLibros",
            "summary": "Esta\u0020funcion\u0020busca\u0020la\u0020tabla\u0020de\u0020libros,\u0020a\u0020la\u0020vez\u0020con\u0020el\u0020nombre\ndel\u0020profesor\u0020jefe\u0020designado\u0020a\u0020ese\u0020libro\u0020del\u0020curso",
            "url": "classes/LibroCursos.html#method_obtenerLibros"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024id_libro",
            "name": "id_libro",
            "summary": "",
            "url": "classes/LibroCursos.html#property_id_libro"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024id_empleado",
            "name": "id_empleado",
            "summary": "",
            "url": "classes/LibroCursos.html#property_id_empleado"
        },                {
            "fqsen": "\\LibroCursos\u003A\u003A\u0024observaciones",
            "name": "observaciones",
            "summary": "",
            "url": "classes/LibroCursos.html#property_observaciones"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
